bibentries <- list(
  "WorldClim" = bibentry(bibtype = "Article",
                         author = c(
                           person(c("Robert","J."), "Hijmans"), person(c("Susan", "E."), "Cameron"),
                           person(c("Juan","L."), "Parra"), person(c("Peter", "G."), "Jones"), 
                           person("Andy", "Jarvis")),
                         title = "Very high resolution interpolated climate surfaces for global land areas.",
                         journal = "International Journal of Climatology",
                         year = 2005, volume = 25, number = 15, pages = "1965-1978",
                         doi = "10.1002/joc.1276", key = "WorldClim"),
  "Bio-ORACLE" = bibentry(bibtype = "Article",
                          author = c(
                            person("Lennert", "Tyberghein"), person("Verbruggen", "Heroen"),
                            person("Klaas", "Pauly"), person("Charles", "Troupin"),
                            person("Frederic", "Mineur"), person("Olivier", "De Clerck")),
                          title = "Bio-ORACLE: a global environmental dataset for marine species distribution modelling",
                          journal = "Global Ecology and Biogeography",
                          year = 2012, volume = 21, number = 2, pages = "272-281",
                          doi = "10.1111/j.1466-8238.2011.00656.x", key = "Bio-ORACLE"),
  "Bio-ORACLE_Future" = bibentry(bibtype = "Article",
                                 author = c(
                                   person("Alexander", "Jueterbock"), person("Lennert", "Tyberghein"), 
                                   person("Verbruggen", "Heroen"), person(c("James", "A."), "Coyer"),
                                   person(c("Jeanine", "L."), "Olsen"), person("Galice", "Hoarau")),
                                 title = "Climate change impact on seaweed meadow distribution in the North Atlantic rocky intertidal", 
                                 journal = "Ecology and Evolution",
                                 year = 2013, volume = 3, number = 5, pages = "1356-1373",
                                 doi = "", key = "Bio-ORACLE_Future"),
  "MARSPEC" = bibentry(bibtype = "Article",
                       author = c(
                         person(c("Elizabeth", "J."), "Sbrocco"), person(c("Paul", "H."), "Barber")),
                       title = "MARSPEC: ocean climate layers for marine spatial ecology",
                       year = 2013, volume = 94, number = 4, pages = "979",
                       journal = "Ecology",
                       doi = "10.1890/12-1358.1", key = "MARSPEC"), 
  "Paleo-MARSPEC" = bibentry(bibtype = "Article",
                             author = person(c("Elizabeth", "J."), "Sbrocco"),
                             title = "Paleo-MARSPEC: gridded ocean climate layers for the mid-Holocene and Last Glacial Maximum",
                             journal = "Ecology",
                             year = 2014, volume = 95, number = 6, pages = "1710",
                             doi = "10.1890/14-0443.1", key = "Paleo-MARSPEC"),
  "ENVIREM" = bibentry(bibtype = "Article",
                       author = c(person(c("Pascal", "O."), "Title"), person(c("Jordan", "B."), "Bemmels")),
                       title = "ENVIREM: An expanded set of bioclimatic and topographic variables increases flexibility and improves performance of ecological niche modeling.",
                       year = 2017, 
                       journal = "Ecography", doi = "10.1111/ecog.02880", key = "ENVIREM"),
  lnk_bibentry = list("future" = list("Bio-ORACLE" = "Bio-ORACLE_Future"),
                      "paleo" = list("MARSPEC" = "Paleo-MARSPEC"),
                      "layers" = list()))


